name: Publish to Github Pages

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  run:
    name: Publish Web App
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Build Web App
        run: yarn build
      - name: Publish to GitHub pages
        run: |
          echo "machine github.com login accesskey password ${{ secrets.TOKEN }}" > ~/.netrc
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          cd build
          git init
          git add -A
          git commit -m "update Web App"
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git push -f origin HEAD:gh-pages
